{% set name = "tptp-lark-parser" %}
{% set version = "0.0.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/tptp-lark-parser-{{ version }}.tar.gz
  sha256: 1b0353570d45d520535ccd6ed976ca3e73a7ad3ea4f24f34df3059a3a4cab445

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.7
    - poetry-core >=1.0.0
  run:
    - importlib_resources
    - lark-parser
    - python >=3.7

test:
  imports:
    - tptp_lark_parser
  source_files:
    - tptp_lark_parser
  commands:
    - pip check
    - pytest --doctest-modules tptp_lark_parser
  requires:
    - pip
    - pytest

about:
  home: https://github.com/inpefess/tptp-lark-parser
  summary: A TPTP parser using Lark
  license: Apache-2.0
  license_file: LICENSE
  doc_url: https://tptp-lark-parser.readthedocs.io/
  dev_url: https://github.com/inpefess/tptp-lark-parser

extra:
  recipe-maintainers:
    - inpefess
